import Link from 'next/link'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'

import { OrderSummary } from '@/components/site/order-summary'
import { RegisterSteps } from '@/components/site/register-steps'
import { Button, ButtonLink } from '@/components/ui/button'
import { Badge, Card } from '@/components/ui/card'
import { Icon } from '@/components/ui/icon'
import {
  Breadcrumbs,
  CardGrid,
  Container,
  Section,
} from '@/components/ui/layout'
import { db } from '@/lib/db'
import {
  PAYMENT_METHOD_LABELS,
  PaymentStatus,
  RegistrationStatus,
  type PaymentMethod,
} from '@/lib/enums'
import { formatDate, formatDateRange } from '@/lib/format'
import { formatMoney, isCurrency, type Currency } from '@/lib/money'
import { isSandboxMode } from '@/lib/payments/gateways'
import { sandboxApprove, sandboxDecline } from '@/lib/actions/sandbox'
import { renderQrSvg } from '@/lib/tickets'

/**
 * Register — step 4, confirmation (§4.9 "on-screen success + emailed/SMS
 * receipt and QR e-ticket").
 *
 * Also the status page a delegate returns to. The four states it has to render
 * honestly are: confirmed, awaiting a mobile-money approval, awaiting an
 * offline transfer, and failed. Each one says what has happened and what the
 * delegate should do next — "pending" on its own is the most anxiety-producing
 * word a payment page can show.
 *
 * QR codes are rendered here as inline SVG rather than linked images, so the
 * ticket is on screen the moment the page paints even if the connection drops
 * afterwards — which is exactly the situation at a registration desk.
 */

export const metadata: Metadata = {
  title: 'Your registration',
  robots: { index: false, follow: false },
}

type Params = { reference: string }

export default async function RegistrationStatusPage({
  params,
}: {
  params: Promise<Params>
}) {
  const { reference } = await params

  const registration = await db.registration.findUnique({
    where: { reference },
    include: {
      event: true,
      ticketType: { select: { name: true } },
      payment: { include: { invoice: true } },
      delegates: { orderBy: { createdAt: 'asc' } },
    },
  })

  if (!registration) notFound()

  const currency: Currency = isCurrency(registration.currency)
    ? registration.currency
    : 'SLE'

  const payment = registration.payment
  const confirmed = registration.status === RegistrationStatus.CONFIRMED

  // Rendering N QR codes is CPU work; they are generated in parallel and only
  // for a confirmed registration, so a pending page costs nothing.
  const tickets = confirmed
    ? await Promise.all(
        registration.delegates.map(async (delegate) => ({
          id: delegate.id,
          name: `${delegate.firstName} ${delegate.lastName}`,
          code: delegate.ticketCode,
          svg: await renderQrSvg(delegate.qrPayload),
        })),
      )
    : []

  return (
    <>
      <Breadcrumbs
        items={[
          { label: 'Home', href: '/' },
          { label: 'Register', href: '/register' },
          { label: 'Your registration', href: `/register/${reference}` },
        ]}
      />
      <RegisterSteps current={4} />

      {/* ── Status banner ────────────────────────────────────────────────── */}

      <Section
        tone={confirmed ? 'forest' : 'white'}
        size="wide"
        className="py-10 sm:py-12"
      >
        <StatusBanner
          registration={registration}
          payment={payment}
          currency={currency}
        />
      </Section>

      {/* ── Tickets ──────────────────────────────────────────────────────── */}

      {confirmed && tickets.length > 0 && (
        <Section tone="white" size="wide">
          <h2 className="text-2xl text-ink-950 sm:text-3xl">
            Your e-ticket{tickets.length === 1 ? '' : 's'}
          </h2>
          <p className="mt-3 max-w-2xl text-ink-600">
            Show the QR code at the registration desk — on your phone is fine,
            there is nothing to print. The same codes have been emailed to{' '}
            {registration.email}.
          </p>

          <CardGrid columns={3} className="mt-8">
            {tickets.map((ticket, index) => (
              <Card key={ticket.id} className="text-center">
                <p className="text-xs font-semibold uppercase tracking-wider text-forest-700">
                  Delegate {index + 1} of {tickets.length}
                </p>

                <div
                  /*
                   * The SVG is generated by the qrcode library from an opaque
                   * signed code — it contains no delegate data and no
                   * user-supplied string, so there is nothing here for an
                   * injected script to ride in on (NFR-05).
                   */
                  className="mx-auto mt-4 w-40 [&>svg]:size-full"
                  dangerouslySetInnerHTML={{ __html: ticket.svg }}
                />

                <p className="mt-4 font-display text-lg font-bold tracking-wide text-ink-950">
                  {ticket.code}
                </p>
                <p className="mt-1 text-sm text-ink-600">{ticket.name}</p>
              </Card>
            ))}
          </CardGrid>

          {registration.quantity > 1 && (
            <div className="mt-8 flex gap-3 rounded-xl bg-ink-50 p-5">
              <Icon
                name="users"
                className="mt-0.5 size-5 shrink-0 text-ink-500"
              />
              <p className="text-sm leading-relaxed text-ink-600">
                Every ticket is currently in your name. To name the individual
                delegates — so their badges are right and the desk can find
                them — sign in to the portal, or email the secretariat with
                your reference.
              </p>
            </div>
          )}
        </Section>
      )}

      {/*
        Sandbox only. Mobile money in sandbox never receives a webhook, so
        without this the local flow stops at "approve the prompt on your phone"
        and the half of the system that issues tickets and writes the ledger
        can never be exercised. The actions refuse to run in live mode
        regardless of what is rendered here (lib/actions/sandbox.ts).
      */}
      {isSandboxMode() &&
        !confirmed &&
        payment &&
        payment.status !== PaymentStatus.PAID && (
          <Section tone="white" size="wide" className="py-0">
            <div className="rounded-xl bg-amber-50 p-5 ring-1 ring-inset ring-amber-200">
              <p className="text-sm font-semibold text-amber-900">
                Sandbox — stand in for the provider
              </p>
              <p className="mt-1 text-sm text-amber-900/80">
                No prompt will reach a real handset. Use these to simulate what
                the provider’s webhook would tell us.
              </p>

              <div className="mt-4 flex flex-col gap-3 sm:flex-row">
                <form action={sandboxApprove}>
                  <input
                    type="hidden"
                    name="reference"
                    value={payment.reference}
                  />
                  <input
                    type="hidden"
                    name="back"
                    value={`/register/${reference}`}
                  />
                  <Button type="submit" variant="primary">
                    Simulate approval
                  </Button>
                </form>

                <form action={sandboxDecline}>
                  <input
                    type="hidden"
                    name="reference"
                    value={payment.reference}
                  />
                  <input
                    type="hidden"
                    name="back"
                    value={`/register/${reference}`}
                  />
                  <Button type="submit" variant="outline">
                    Simulate decline
                  </Button>
                </form>
              </div>
            </div>
          </Section>
        )}

      {/* ── What happens next ────────────────────────────────────────────── */}

      <Section tone="muted" size="wide">
        <div className="grid gap-10 lg:grid-cols-12 lg:gap-12">
          <div className="lg:col-span-7">
            <h2 className="text-xl text-ink-950 sm:text-2xl">
              {confirmed ? 'Before the forum' : 'What happens next'}
            </h2>

            <ol className="mt-6 space-y-5">
              {(confirmed ? CONFIRMED_STEPS : pendingSteps(payment)).map(
                (step, index) => (
                  <li key={step.title} className="flex gap-4">
                    <span
                      aria-hidden="true"
                      className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white font-display text-sm font-bold text-forest-700 ring-1 ring-ink-200"
                    >
                      {index + 1}
                    </span>
                    <div>
                      <h3 className="font-display text-base font-semibold text-ink-950">
                        {step.title}
                      </h3>
                      <p className="mt-1 text-sm leading-relaxed text-ink-600">
                        {step.body}
                      </p>
                    </div>
                  </li>
                ),
              )}
            </ol>
          </div>

          <div className="lg:col-span-5">
            <OrderSummary
              title="Your order"
              ticketName={registration.ticketType.name}
              quantity={registration.quantity}
              currency={currency}
              subtotalMinor={registration.subtotalMinor}
              discounts={
                registration.discountMinor > 0
                  ? [
                      {
                        kind: 'PROMO',
                        label: 'Discounts applied',
                        amountMinor: registration.discountMinor,
                      },
                    ]
                  : []
              }
              totalMinor={registration.totalMinor}
            >
              <dl className="space-y-3 border-t border-ink-200 pt-5 text-sm">
                <SummaryRow label="Reference" value={registration.reference} />
                <SummaryRow
                  label="Name"
                  value={`${registration.firstName} ${registration.lastName}`}
                />
                <SummaryRow label="Email" value={registration.email} />
                {payment && (
                  <SummaryRow
                    label="Paying by"
                    value={
                      PAYMENT_METHOD_LABELS[payment.method as PaymentMethod] ??
                      payment.method
                    }
                  />
                )}
                {payment?.invoice && (
                  <SummaryRow label="Invoice" value={payment.invoice.number} />
                )}
              </dl>
            </OrderSummary>
          </div>
        </div>
      </Section>

      <Section tone="white">
        <Container size="narrow" className="px-0">
          <h2 className="text-xl text-ink-950">Something not right?</h2>
          <p className="mt-3 leading-relaxed text-ink-700">
            Quote reference{' '}
            <strong className="text-ink-950">{registration.reference}</strong>{' '}
            and the secretariat can find your registration immediately.
          </p>
          <div className="mt-6 flex flex-col gap-3 sm:flex-row">
            <ButtonLink href="/contact" variant="primary">
              Contact the secretariat
            </ButtonLink>
            <ButtonLink href="/events/agenda" variant="outline">
              See the programme
            </ButtonLink>
          </div>
        </Container>
      </Section>
    </>
  )
}

// ── Status banner ───────────────────────────────────────────────────────────

type RegistrationRow = {
  reference: string
  status: string
  quantity: number
  totalMinor: number
  firstName: string
  email: string
  confirmedAt: Date | null
  event: {
    name: string
    startDate: Date
    endDate: Date
    venueName: string
    city: string
  }
}

type PaymentRow = {
  status: string
  method: string
  failureReason: string | null
  invoice: { number: string; dueAt: Date | null } | null
} | null

function StatusBanner({
  registration,
  payment,
  currency,
}: {
  registration: RegistrationRow
  payment: PaymentRow
  currency: Currency
}) {
  if (registration.status === RegistrationStatus.CONFIRMED) {
    return (
      <div className="max-w-3xl">
        <Icon name="check" className="size-10 text-gold-300" />
        <h1 className="mt-5 font-display text-3xl font-extrabold leading-tight text-white sm:text-4xl">
          You are registered
        </h1>
        <p className="mt-4 text-lg text-white/85">
          {registration.event.name},{' '}
          {formatDateRange(
            registration.event.startDate,
            registration.event.endDate,
          )}
          , at {registration.event.venueName}, {registration.event.city}.
        </p>
        <p className="mt-3 text-white/70">
          Reference{' '}
          <span className="font-semibold text-white">
            {registration.reference}
          </span>
          {registration.confirmedAt &&
            ` · confirmed ${formatDate(registration.confirmedAt)}`}
        </p>
      </div>
    )
  }

  if (registration.status === RegistrationStatus.CANCELLED) {
    return (
      <div className="max-w-3xl">
        <Badge tone="danger">Cancelled</Badge>
        <h1 className="mt-4 text-3xl text-ink-950 sm:text-4xl">
          This registration was cancelled
        </h1>
        <p className="mt-4 text-ink-700">
          Nothing is owed. If this was not expected, quote reference{' '}
          {registration.reference} to the secretariat.
        </p>
        <ButtonLink href="/register" variant="primary" className="mt-6">
          Register again
        </ButtonLink>
      </div>
    )
  }

  if (payment?.status === PaymentStatus.FAILED) {
    return (
      <div className="max-w-3xl">
        <Badge tone="danger">Payment failed</Badge>
        <h1 className="mt-4 text-3xl text-ink-950 sm:text-4xl">
          That payment did not go through
        </h1>
        <p className="mt-4 text-ink-700">
          {payment.failureReason ??
            'The payment was not completed. Nothing has been charged.'}{' '}
          Your place is still held — try again, or choose a different method.
        </p>
        <ButtonLink
          href={`/register/${registration.reference}/pay`}
          variant="accent"
          size="lg"
          className="mt-6 rounded-none font-semibold uppercase tracking-wider"
        >
          Try again
        </ButtonLink>
      </div>
    )
  }

  if (payment?.invoice) {
    return (
      <div className="max-w-3xl">
        <Badge tone="warning">Awaiting payment</Badge>
        <h1 className="mt-4 text-3xl text-ink-950 sm:text-4xl">
          Invoice {payment.invoice.number} has been issued
        </h1>
        <p className="mt-4 text-ink-700">
          {formatMoney(registration.totalMinor, currency, { withCode: true })}{' '}
          is due
          {payment.invoice.dueAt && ` by ${formatDate(payment.invoice.dueAt)}`}.
          Your place is held until then. Quote reference{' '}
          <strong className="text-ink-950">{registration.reference}</strong>{' '}
          when you pay, and your e-ticket is issued as soon as it clears.
        </p>
        <p className="mt-3 text-sm text-ink-600">
          The invoice and our bank details have been emailed to{' '}
          {registration.email}.
        </p>
      </div>
    )
  }

  return (
    <div className="max-w-3xl">
      <Badge tone="warning">Awaiting confirmation</Badge>
      <h1 className="mt-4 text-3xl text-ink-950 sm:text-4xl">
        Approve the prompt on your phone
      </h1>
      <p className="mt-4 text-ink-700">
        We have sent a payment request for{' '}
        {formatMoney(registration.totalMinor, currency, { withCode: true })} to
        your{' '}
        {PAYMENT_METHOD_LABELS[payment?.method as PaymentMethod] ??
          'mobile money'}{' '}
        wallet. Approve it with your PIN and this page will show your e-ticket.
      </p>
      <p className="mt-3 text-sm text-ink-600">
        Nothing arrived? Reload this page in a minute — confirmations can lag
        the prompt.{' '}
        <Link
          href={`/register/${registration.reference}/pay`}
          className="font-medium text-forest-700 hover:underline"
        >
          Or choose a different payment method.
        </Link>
      </p>
    </div>
  )
}

// ── Next steps ──────────────────────────────────────────────────────────────

const CONFIRMED_STEPS = [
  {
    title: 'Keep the QR code',
    body: 'It is on this page, in your email, and in the portal if you have an account. Any of the three works at the desk.',
  },
  {
    title: 'Plan the trip',
    body: 'Venue, hotels and visa guidance are on the venue & travel page. Ask the secretariat for a visa invitation letter if you need one.',
  },
  {
    title: 'Build your programme',
    body: 'Roundtables and workshops have capped numbers, and they fill up. The agenda shows what runs when.',
  },
]

function pendingSteps(payment: PaymentRow) {
  if (payment?.invoice) {
    return [
      {
        title: 'Pay the invoice',
        body: 'Bank details are on the invoice we emailed you. Quote your registration reference on the transfer.',
      },
      {
        title: 'Send the remittance advice',
        body: 'Email it to finance@fbf.sl. It is what lets the secretariat match your payment on the day it arrives rather than the week after.',
      },
      {
        title: 'Your e-ticket is issued',
        body: 'As soon as the payment clears, your place is confirmed and the QR code is emailed to you.',
      },
    ]
  }

  return [
    {
      title: 'Approve the payment',
      body: 'Enter your wallet PIN on the prompt sent to your handset.',
    },
    {
      title: 'We confirm automatically',
      body: 'Your provider tells us the moment it clears — there is nothing else for you to do.',
    },
    {
      title: 'Your e-ticket arrives',
      body: 'On this page, and by email and SMS to the details you gave us.',
    },
  ]
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <dt className="text-ink-600">{label}</dt>
      <dd className="shrink-0 text-right font-medium text-ink-950">{value}</dd>
    </div>
  )
}
